blank_issues_enabled: false
contact_links:
  - name: Frigate Support
    url: https://github.com/blakeblackshear/frigate/discussions/new/choose
    about: Get support for setting up or troubleshooting Frigate.
  - name: Frigate Bug Report
    url: https://github.com/blakeblackshear/frigate/discussions/new/choose
    about: Report a specific UI or backend bug.
